### ISSUE TITLE
Possible bug in calculate_value_dr_risk

### ISSUE THREAD

**Issue by stoddardg** [divyat09/cate-estimator-selection#1]
Hi, 

I have been reading your paper and the accompanying codebase with great interest. Let me first say that both the paper are very informative, so thank you so much. 

In my effort to understand some of the evaluation metrics better, I think I might have encountered a small bug in computing value_dr_risk. Specifically, on this [line](https://github.com/divyat09/cate-estimator-selection/blob/a5dea682bf97dfbbe3940924f3375d866eb9c1f4/utils/evaluation.py#L553C22-L553C37) 

`value_dr_score = decision_policy * (mu_1 - mu_0 + (2 * t - 1) * (y - mu) / prop_score)`

It seems that the entire term is multiplied by `decision_policy`, which doesn't match equation 10 in the paper (https://arxiv.org/pdf/2211.01939.pdf) where only the propensity-weighted outcome is multiplied by the indicator for whether the observed assignment matches the policy. The result is that there's value of 0 for any observation that doesn't match the policy, which I think is wrong. 

It's very possible that I'm misunderstanding the method, but I figured I would raise the issue just in case. 

Thanks!

**Comment by divyat09** [comment]
Thanks for your comment! So equation 10 in the paper only refers to the doubly robust potential outcome and does not take into consideration the treatment assignment based on the policy. As mentioned in the Value DR score in the paper, the entire term is indeed multiplied by the decision policy. This is also consistent with the Value DR score (eq 6) in Schuler et al. (https://arxiv.org/pdf/1804.05146.pdf).

**Comment by stoddardg** [comment]
Ah, thanks makes sense. Thanks for the quick response and the reference.
